import { 
  people01, 
  people02, 
  people03, 
  facebook, 
  instagram, 
  linkedin, 
  twitter, 
  airbnb, 
  binance, 
  coinbase, 
  dropbox, 
  send, 
  shield, 
  star
} from "../assets";

export const navLinks = [
  {
    id: "home",
    title: "Home",
  },
  // {
  //   id: "shop",
  //   title: "Shop",
  // },
  {
    id: "substores",
    title: "Substores",
  },
  {
    id: "about",
    title: "About",
  },
];

export const features = [
  {
    id: "feature-1",
    icon: star,
    title: "Innovation-Driven",
    content:
      "We deliver cutting-edge technology solutions tailored to your needs.",
  },
  {
    id: "feature-2",
    icon: shield,
    title: "100% Secure",
    content:
      "We implement advanced security measures to protect your data and projects.",
  },
  {
    id: "feature-3",
    icon: send,
    title: "Seamless Integration",
    content:
      "Our solutions ensure smooth performance and compatibility across platforms.",
  },
];

export const feedback = [
  {
    id: "feedback-1",
    content:
      "Money is only a tool. It will take you wherever you wish, but it will not replace you as the driver.",
    name: "Herman Jensen",
    title: "Founder & Leader",
    img: people01,
  },
  {
    id: "feedback-2",
    content:
      "Money makes your life easier. If you're lucky to have it, you're lucky.",
    name: "Steve Mark",
    title: "Founder & Leader",
    img: people02,
  },
  {
    id: "feedback-3",
    content:
      "It is usually people in the money business, finance, and international trade that are really rich.",
    name: "Kenn Gallagher",
    title: "Founder & Leader",
    img: people03,
  },
];

export const stats = [
  {
    id: "stats-1",
    title: "Success Rate",
    value: "99.9%",
  },
  {
    id: "stats-2",
    title: "Transactions",
    value: "10K+",
  },
  {
    id: "stats-3",
    title: "Response Time",
    value: "<2s",
  },
];

export const footerLinks = [
  // {
  //   title: "Shop",
  //   links: [
  //     {
  //       name: "All Products",
  //       link: "#shop",
  //     },
  //     {
  //       name: "Categories",
  //       link: "#categories",
  //     },
  //     {
  //       name: "Substores",
  //       link: "#substores",
  //     },
  //     {
  //       name: "New Arrivals",
  //       link: "#new-arrivals",
  //     },
  //     {
  //       name: "Best Sellers",
  //       link: "#best-sellers",
  //     },
  //   ],
  // },
  {
    title: "Customer Service",
    links: [
      {
        name: "Contact Us",
        link: "#contact",
      },
      {
        name: "Shipping Info",
        link: "#shipping",
      },
      {
        name: "Returns",
        link: "#returns",
      },
      {
        name: "FAQ",
        link: "#faq",
      },
      {
        name: "Track Order",
        link: "#track-order",
      },
    ],
  },
  {
    title: "About",
    links: [
      {
        name: "About Us",
        link: "#about",
      },
      {
        name: "Become a Seller",
        link: "#become-seller",
      },
      {
        name: "Privacy Policy",
        link: "#privacy",
      },
      {
        name: "Terms & Conditions",
        link: "#terms",
      },
    ],
  },
];

export const socialMedia = [
  {
    id: "social-media-1",
    icon: instagram,
    link: "https://www.instagram.com/",
  },
  {
    id: "social-media-2",
    icon: facebook,
    link: "https://www.facebook.com/",
  },
  {
    id: "social-media-3",
    icon: twitter,
    link: "https://www.twitter.com/",
  },
  {
    id: "social-media-4",
    icon: linkedin,
    link: "https://www.linkedin.com/",
  },
];

export const clients = [
  {
    id: "client-1",
    logo: airbnb,
  },
  {
    id: "client-2",
    logo: binance,
  },
  {
    id: "client-3",
    logo: coinbase,
  },
  {
    id: "client-4",
    logo: dropbox,
  },
];

// E-commerce Categories
export const categories = [
  {
    id: "cat-1",
    name: "Electronics",
    description: "Latest gadgets and tech products",
    icon: star,
  },
  {
    id: "cat-2",
    name: "Fashion",
    description: "Trendy clothing and accessories",
    icon: shield,
  },
  {
    id: "cat-3",
    name: "Home & Living",
    description: "Furniture and home decor",
    icon: send,
  },
  {
    id: "cat-4",
    name: "Sports & Outdoors",
    description: "Sports equipment and outdoor gear",
    icon: star,
  },
  {
    id: "cat-5",
    name: "Books & Media",
    description: "Books, movies, and music",
    icon: shield,
  },
  {
    id: "cat-6",
    name: "Beauty & Health",
    description: "Cosmetics and wellness products",
    icon: send,
  },
];

// Substores
export const substores = [
  {
    id: "substore-1",
    name: "Grid Mart Store",
    description: "Your one-stop shop for quality products and essentials",
    category: "General Store",
    rating: 4.7,
    productsCount: 50,
    image: people01,
    featured: true,
    url: "https://gridmartstore.myshopify.com/",
    logo: "/Watch-logo.png",
  },
  {
    id: "substore-2",
    name: "TinyHeaven",
    description: "Curated collection of delightful products for your lifestyle",
    category: "Lifestyle & Gifts",
    rating: 4.8,
    productsCount: 35,
    image: people02,
    featured: true,
    url: "https://tinyyheaven.myshopify.com/",
    logo: "/Tiny-Heaven-Logo.png",
  },
  {
    id: "substore-3",
    name: "Oxtenfeet",
    description: "Premium footwear and accessories for modern living",
    category: "Fashion & Footwear",
    rating: 4.9,
    productsCount: 28,
    image: people03,
    featured: true,
    url: "https://oxtenfeet.myshopify.com/",
    logo: "/Oxtenfeet-Logo.png",
  },
  {
    id: "substore-4",
    name: "Men's Exontime",
    description: "Premium men's fashion and accessories for the modern gentleman",
    category: "Men's Fashion",
    rating: 4.8,
    productsCount: 42,
    image: people01,
    featured: true,
    url: "https://mensexontime.myshopify.com/",
    logo: "/Men's Exontime.png",
  },
  {
    id: "substore-5",
    name: "RoomVerse",
    description: "Transform your space with stylish home decor and furnishings",
    category: "Home & Living",
    rating: 4.7,
    productsCount: 55,
    image: people02,
    featured: true,
    url: "https://rooomverse.myshopify.com/",
    logo: "/RoomVerse-logo.png",
  },
  {
    id: "substore-6",
    name: "Snowboard Vendor",
    description: "Complete snowboard gear for all skill levels",
    category: "Sports & Outdoors",
    rating: 4.8,
    productsCount: 1,
    image: people01,
    featured: false,
  },
  {
    id: "substore-5",
    name: "Multi-managed Vendor",
    description: "Quality multi-managed snowboards and equipment",
    category: "Sports & Outdoors",
    rating: 4.7,
    productsCount: 1,
    image: people02,
    featured: false,
  },
];

// Products
export const products = [
  {
    id: "example-hat",
    name: "Example Beanie",
    description: "Our beanie is a must-have accessory from our heritage brand and dead stock yarn. Made with recycled materials, it not only adds style but also promotes sustainability. Expertly crafted using 100% cotton yarns, making it both unique and super soft.",
    price: 16.19,
    originalPrice: 22.99,
    discount: 30,
    category: "Fashion",
    substore: "Acme Store",
    rating: 4.6,
    reviews: 245,
    image: "https://cdn.shopify.com/s/files/1/0976/3959/6381/files/kids-beanie.jpg?v=1755056828",
    inStock: false,
    featured: false,
    tags: ["Hat", "Fashion", "Accessories"],
  },
  {
    id: "example-pants",
    name: "Example Jeans",
    description: "Our jeans feature a light and classic stone wash, perfect for achieving a timeless look. These jeans can be rolled at the cuff for a casual and versatile style. Upgrade your wardrobe and embrace classic fashion with our denim.",
    price: 85.50,
    originalPrice: 64.95,
    discount: 0,
    category: "Fashion",
    substore: "Acme Store",
    rating: 4.7,
    reviews: 312,
    image: "https://cdn.shopify.com/s/files/1/0976/3959/6381/files/urban-vintage-denimn-on-hangers.jpg?v=1755056827",
    inStock: false,
    featured: false,
    tags: ["Original", "Pants", "Denim"],
  },
  {
    id: "example-shirt",
    name: "Example T-Shirt",
    description: "This t-shirt is as simple as it gets. Easy to wear and insanely comfortable. Plus, it's made right here in our store for that extra special touch. Order a custom design or keep it blank for a classic look you can print on.",
    price: 25.00,
    originalPrice: null,
    discount: 0,
    category: "Fashion",
    substore: "Acme Store",
    rating: 4.8,
    reviews: 567,
    image: "https://cdn.shopify.com/s/files/1/0976/3959/6381/files/tshirts.jpg?v=1755056825",
    inStock: true,
    featured: true,
    tags: ["Made to Order", "Shirt", "Cotton"],
  },
  {
    id: "the-3p-fulfilled-snowboard",
    name: "The 3p Fulfilled Snowboard",
    description: "Top and bottom view of a snowboard featuring 7 stacked hexagons on top and a small, centred hexagonal logo for Hydrogen on the bottom. Premium quality snowboard for winter sports enthusiasts.",
    price: 2629.95,
    originalPrice: null,
    discount: 0,
    category: "Sports & Outdoors",
    substore: "Smart Bulk Store",
    rating: 4.9,
    reviews: 89,
    image: "https://cdn.shopify.com/s/files/1/0976/3959/6381/files/Main_b9e0da7f-db89-4d41-83f0-7f417b02831d.jpg?v=1755056793",
    inStock: true,
    featured: true,
    tags: ["Accessory", "Sport", "Winter"],
  },
  {
    id: "the-multi-managed-snowboard",
    name: "The Multi-managed Snowboard",
    description: "Top and bottom view featuring an illustration with varied outlined shapes in black. The bottom shows a black box character with an H pointing, surrounded by black outlined illustrative elements.",
    price: 629.95,
    originalPrice: null,
    discount: 0,
    category: "Sports & Outdoors",
    substore: "Multi-managed Vendor",
    rating: 4.7,
    reviews: 134,
    image: "https://cdn.shopify.com/s/files/1/0976/3959/6381/files/Main_9129b69a-0c7b-4f66-b6cf-c4222f18028a.jpg?v=1755056794",
    inStock: true,
    featured: true,
    tags: ["Premium", "Snow", "Snowboard", "Sport", "Winter"],
  },
  {
    id: "the-multi-location-snowboard",
    name: "The Multi-location Snowboard",
    description: "Features a pixelated Shopify bag logo and character reviewing a clipboard with a questioning expression with a bright green-blue background. Pattern of many pixel characters on bottom view.",
    price: 729.95,
    originalPrice: null,
    discount: 0,
    category: "Sports & Outdoors",
    substore: "Smart Bulk Store",
    rating: 4.6,
    reviews: 98,
    image: "https://cdn.shopify.com/s/files/1/0976/3959/6381/files/Main_0a4e9096-021a-4c1e-8750-24b233166a12.jpg?v=1755056793",
    inStock: true,
    featured: true,
    tags: ["Premium", "Snow", "Snowboard", "Sport", "Winter"],
  },
  {
    id: "the-collection-snowboard-liquid",
    name: "The Collection Snowboard: Liquid",
    description: "Stylized scene of water, trees, mountains, sky and a moon in blue colours. The bottom view has a blue liquid, drippy background with the text 'liquid' in a stylized script typeface.",
    price: 749.95,
    originalPrice: null,
    discount: 0,
    category: "Sports & Outdoors",
    substore: "Hydrogen Vendor",
    rating: 4.8,
    reviews: 156,
    image: "https://cdn.shopify.com/s/files/1/0976/3959/6381/files/Main_b13ad453-477c-4ed1-9b43-81f3345adfd6.jpg?v=1755056794",
    inStock: true,
    featured: true,
    tags: ["Accessory", "Sport", "Winter"],
  },
  {
    id: "the-collection-snowboard-oxygen",
    name: "The Collection Snowboard: Oxygen",
    description: "Stylized scene of trees, mountains, sky and a sun in red colours. Bottom view has blue wavy lines with the text 'Oxygen' in a stylized script typeface.",
    price: 1025.00,
    originalPrice: null,
    discount: 0,
    category: "Sports & Outdoors",
    substore: "Hydrogen Vendor",
    rating: 4.9,
    reviews: 203,
    image: "https://cdn.shopify.com/s/files/1/0976/3959/6381/files/Main_d624f226-0a89-4fe1-b333-0d1548b43c06.jpg?v=1755056793",
    inStock: true,
    featured: true,
    tags: ["Accessory", "Sport", "Winter"],
  },
  {
    id: "the-complete-snowboard",
    name: "The Complete Snowboard",
    description: "This PREMIUM snowboard is so SUPERDUPER awesome! Abstract circles and lines in shades of teal on top. Bottom view shows abstract circles and lines in shades of purple and blue with SHOPIFY text.",
    price: 699.95,
    originalPrice: null,
    discount: 0,
    category: "Sports & Outdoors",
    substore: "Snowboard Vendor",
    rating: 4.8,
    reviews: 278,
    image: "https://cdn.shopify.com/s/files/1/0976/3959/6381/files/Main_589fc064-24a2-4236-9eaf-13b2bd35d21d.jpg?v=1755056792",
    inStock: true,
    featured: true,
    tags: ["Premium", "Snow", "Snowboard", "Sport", "Winter"],
  },
  {
    id: "the-collection-snowboard-hydrogen",
    name: "The Collection Snowboard: Hydrogen",
    description: "Top view shows stylized hydrogen bonds and the bottom view shows 'H2' in a brush script typeface. Perfect for chemistry and winter sports enthusiasts.",
    price: 600.00,
    originalPrice: null,
    discount: 0,
    category: "Sports & Outdoors",
    substore: "Hydrogen Vendor",
    rating: 4.7,
    reviews: 167,
    image: "https://cdn.shopify.com/s/files/1/0976/3959/6381/files/Main_0a40b01b-5021-48c1-80d1-aa8ab4876d3d.jpg?v=1755056793",
    inStock: true,
    featured: false,
    tags: ["Accessory", "Sport", "Winter"],
  },
  {
    id: "selling-plans-ski-wax",
    name: "Selling Plans Ski Wax",
    description: "A bar of golden yellow wax perfect for maintaining your skis and snowboards. Essential for optimal performance on the slopes.",
    price: 24.95,
    originalPrice: null,
    discount: 0,
    category: "Sports & Outdoors",
    substore: "Smart Bulk Store",
    rating: 4.5,
    reviews: 89,
    image: "https://cdn.shopify.com/s/files/1/0976/3959/6381/files/snowboard_wax.png?v=1755056794",
    inStock: true,
    featured: false,
    tags: ["Accessory", "Sport", "Winter"],
  },
  {
    id: "the-videographer-snowboard",
    name: "The Videographer Snowboard",
    description: "Top view is turquoise and black with graphics of trees. The bottom view is turquoise with the word hydrogen written in cursive. Perfect for videographers who love winter sports.",
    price: 885.95,
    originalPrice: null,
    discount: 0,
    category: "Sports & Outdoors",
    substore: "Smart Bulk Store",
    rating: 4.6,
    reviews: 112,
    image: "https://cdn.shopify.com/s/files/1/0976/3959/6381/files/Main.jpg?v=1755056793",
    inStock: true,
    featured: false,
    tags: ["Snowboard", "Sport", "Winter"],
  },
  {
    id: "the-out-of-stock-snowboard",
    name: "The Out of Stock Snowboard",
    description: "Top view shows a toggle at the top in shades of blue and yellow. The bottom view shows an abstract illustration of toggles in blues and yellows.",
    price: 885.95,
    originalPrice: null,
    discount: 0,
    category: "Sports & Outdoors",
    substore: "Smart Bulk Store",
    rating: 4.7,
    reviews: 45,
    image: "https://cdn.shopify.com/s/files/1/0976/3959/6381/files/Main_f44a9605-cd62-464d-b095-d45cdaa0d0d7.jpg?v=1755056793",
    inStock: false,
    featured: false,
    tags: ["Accessory", "Sport", "Winter"],
  },
  {
    id: "the-compare-at-price-snowboard",
    name: "The Compare at Price Snowboard",
    description: "Top view shows pixelated clouds, with the top-most one being the shape of the Shopify bag logo. Bottom view has a pixelated cloudy sky with blue, pink and purple colours.",
    price: 707.36,
    originalPrice: 885.95,
    discount: 20,
    category: "Sports & Outdoors",
    substore: "Smart Bulk Store",
    rating: 4.8,
    reviews: 234,
    image: "https://cdn.shopify.com/s/files/1/0976/3959/6381/files/snowboard_sky.png?v=1755056794",
    inStock: true,
    featured: true,
    tags: ["Accessory", "Sport", "Winter"],
  },
  {
    id: "the-inventory-not-tracked-snowboard",
    name: "The Inventory Not Tracked Snowboard",
    description: "Top view shows a centred hexagonal logo for Hydrogen that appears to radiate outwards, with overlapping hexagons at the bottom. Bottom shows an abstract angular grid in purples.",
    price: 454.36,
    originalPrice: null,
    discount: 0,
    category: "Sports & Outdoors",
    substore: "Smart Bulk Store",
    rating: 4.5,
    reviews: 67,
    image: "https://cdn.shopify.com/s/files/1/0976/3959/6381/files/snowboard_purple_hydrogen.png?v=1755056794",
    inStock: true,
    featured: false,
    tags: ["Accessory", "Sport", "Winter"],
  },
];